from __future__ import annotations

from typing import Any

from app.llm import complete_json

REPORT_PROMPT = """Rewrite the following structured workflow notes as a one-page briefing for a non-technical procurement manager.
Keep every number exactly as given. Do not invent suppliers or totals. Return JSON {{"report": "markdown string"}}.

Notes:
{notes}
"""


def _money(n: float, currency: str) -> str:
    try:
        n = float(n)
    except (TypeError, ValueError):
        return str(n)
    if (currency or "").upper() == "USD":
        return f"${n:,.0f}"
    return f"{currency} {n:,.0f}"


def build_report(
    *,
    request: str,
    entities: dict,
    ranking: dict,
    validation: dict,
    po: dict,
    approval: dict,
    tools_used: list,
    status: str,
    llm_polish: bool = False,
) -> str:
    currency = entities.get("currency", "PKR")
    selected = ranking.get("selected") or {}
    rejected = ranking.get("rejected") or []
    weights = ranking.get("weights") or {"price": 0.5, "delivery": 0.3, "warranty": 0.2}
    checks = validation.get("checks") or []

    lines = [
        f"# Workflow completion report",
        "",
        f"**Status:** {status.replace('_', ' ').title()}",
        f"**Request:** {request.strip()}",
        "",
        "## What was requested",
        f"- Item: **{entities.get('item')}**",
        f"- Quantity: **{entities.get('quantity')}**",
        f"- Budget ceiling: **{_money(entities.get('budget') or 0, currency)}**",
        f"- Suppliers to compare: **{entities.get('suppliers_to_compare', 3)}**",
        f"- Approval owner: **{entities.get('approval_target', 'procurement_manager')}** (human — the agent cannot approve spend)",
        "",
        "## Decision",
    ]
    if selected:
        scores = selected.get("scores") or {}
        lines += [
            f"- Selected supplier: **{selected.get('name')}** (`{selected.get('id')}`)",
            f"- Unit price: {_money(selected.get('unit_price') or 0, currency)}",
            f"- Total: **{_money(selected.get('total') or 0, currency)}**",
            f"- Delivery: {selected.get('delivery_days')} days · Warranty: {selected.get('warranty_months')} months · Rating: {selected.get('rating')}",
            f"- Weighted score: **{scores.get('weighted', '—')}** (price {weights.get('price', 0.5)*100:.0f}% / delivery {weights.get('delivery', 0.3)*100:.0f}% / warranty {weights.get('warranty', 0.2)*100:.0f}%)",
            "",
            ranking.get("justification") or "",
        ]
    else:
        lines.append("- No supplier could be selected under the stated ceiling. Workflow escalated.")

    if rejected:
        lines += ["", "## Suppliers rejected"]
        for r in rejected:
            lines.append(f"- **{r.get('name') or r.get('id')}** — {r.get('reason')}")

    if checks:
        lines += ["", "## Validation"]
        for c in checks:
            mark = "PASS" if c.get("ok") else "FAIL"
            lines.append(f"- [{mark}] {c.get('name')}: {c.get('detail')}")

    if po:
        lines += [
            "",
            "## Artifact",
            f"- PO number: **{po.get('po_number', '—')}**",
            f"- File: {po.get('url') or po.get('path') or '—'}",
            f"- Grand total: {_money(po.get('grand_total') or selected.get('total') or 0, currency)}",
        ]

    if approval:
        lines += [
            "",
            "## Approval gate",
            f"- Approval id: {approval.get('id') or approval.get('approval_id') or '—'}",
            f"- Status: **{(approval.get('status') or status).replace('_', ' ')}**",
            f"- Approver: {approval.get('approver') or entities.get('approval_target')}",
        ]

    if tools_used:
        lines += ["", "## Tools invoked", ", ".join(f"`{t}`" for t in tools_used)]

    lines += [
        "",
        "---",
        "_Generated by OrchestrAI. Numbers come from deterministic scoring and validation, not from the language model._",
    ]
    base = "\n".join(lines).strip() + "\n"

    if not llm_polish:
        return base
    parsed, tag = complete_json(REPORT_PROMPT.format(notes=base))
    if parsed and isinstance(parsed.get("report"), str) and parsed["report"].strip():
        extra = parsed["report"].strip()
        if "fallback" not in tag:
            return extra + f"\n\n_Provider: {tag}_\n"
    return base
