"""Purchase order PDF generation via fpdf2."""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

from fpdf import FPDF
from fpdf.enums import XPos, YPos

from app.models import ToolResult
from app.tools import tool

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "generated"
COUNTER_FILE = OUT / "_po_seq.json"


def _next_po() -> str:
    OUT.mkdir(parents=True, exist_ok=True)
    seq = 1
    if COUNTER_FILE.exists():
        try:
            seq = int(json.loads(COUNTER_FILE.read_text()).get("n", 1))
        except Exception:
            seq = 1
    COUNTER_FILE.write_text(json.dumps({"n": seq + 1}))
    return f"PO-2026-{seq:04d}"


def _latin(s: object) -> str:
    text = str(s or "")
    table = str.maketrans({
        "\u2014": "-",
        "\u2013": "-",
        "\u00b7": "|",
        "\u00d7": "x",
        "\u201c": '"',
        "\u201d": '"',
        "\u2018": "'",
        "\u2019": "'",
    })
    return text.translate(table).encode("latin-1", "replace").decode("latin-1")


def _money(n: float, currency: str) -> str:
    if currency.upper() == "USD":
        return f"${n:,.2f}"
    return f"{currency} {n:,.2f}"


class PODoc(FPDF):
    def header(self) -> None:
        self.set_fill_color(14, 18, 24)
        self.rect(0, 0, 210, 28, "F")
        self.set_text_color(62, 224, 178)
        self.set_font("Helvetica", "B", 16)
        self.set_xy(12, 8)
        self.cell(186, 8, "OrchestrAI  /  PURCHASE ORDER")
        self.set_text_color(180, 190, 200)
        self.set_font("Helvetica", "", 9)
        self.set_xy(12, 16)
        self.cell(186, 6, "Generated by an agentic workflow - human approval required before spend is committed.")
        self.set_xy(12, 32)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 130, 140)
        self.cell(0, 8, f"Page {self.page_no()}  |  Not valid until approved  |  OrchestrAI HackHorizon 2026", align="C")


def render_po(
    *,
    po_number: str,
    entities: dict,
    selected: dict,
    ranking: dict | None = None,
) -> Path:
    OUT.mkdir(parents=True, exist_ok=True)
    currency = entities.get("currency", "PKR")
    qty = int(entities.get("quantity") or selected.get("quantity") or 1)
    unit = float(selected.get("unit_price") or 0)
    total = float(selected.get("total") or unit * qty)
    pdf = PODoc()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()
    pdf.set_text_color(20, 24, 28)
    pdf.set_font("Helvetica", "B", 12)
    pdf.ln(8)
    pdf.cell(0, 8, _latin(f"PO Number: {po_number}"))
    pdf.ln(8)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, _latin(f"Date: {date.today().isoformat()}"))
    pdf.ln(6)
    pdf.multi_cell(0, 6, _latin(f"Requester: {str(entities.get('raw_request', ''))[:180]}"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "Supplier")
    pdf.ln(8)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, _latin(f"{selected.get('name')}  ({selected.get('id')})"))
    pdf.ln(6)
    pdf.cell(0, 6, _latin(f"SKU: {selected.get('sku', '-')}    Rating: {selected.get('rating', '-')}"))
    pdf.ln(6)
    pdf.cell(0, 6, _latin(f"Delivery: {selected.get('delivery_days', '-')} days    Warranty: {selected.get('warranty_months', '-')} months"))
    pdf.ln(10)

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "Line items")
    pdf.ln(8)
    pdf.set_fill_color(232, 246, 240)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(80, 8, "Description", border=1, fill=True)
    pdf.cell(25, 8, "Qty", border=1, fill=True, align="R")
    pdf.cell(40, 8, "Unit price", border=1, fill=True, align="R")
    pdf.cell(40, 8, "Line total", border=1, fill=True, align="R")
    pdf.ln()
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(80, 8, _latin(entities.get("item", "item")), border=1)
    pdf.cell(25, 8, str(qty), border=1, align="R")
    pdf.cell(40, 8, _money(unit, currency), border=1, align="R")
    pdf.cell(40, 8, _money(total, currency), border=1, align="R")
    pdf.ln()
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(145, 8, "GRAND TOTAL", border=1, align="R")
    pdf.cell(40, 8, _money(total, currency), border=1, align="R")
    pdf.ln(12)

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "Constraints & scoring")
    pdf.ln(8)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, _latin(f"Budget ceiling: {_money(float(entities.get('budget') or 0), currency)}"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.multi_cell(0, 6, "Scoring weights: price 50% / delivery 30% / warranty 20% (deterministic, not LLM).", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    if ranking and ranking.get("justification"):
        pdf.multi_cell(0, 6, _latin(f"Selection rationale: {ranking['justification']}"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    if ranking and ranking.get("rejected"):
        pdf.multi_cell(0, 6, _latin("Rejected suppliers: " + "; ".join(
            f"{r.get('name')}: {r.get('reason')}" for r in ranking["rejected"]
        )), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 9)
    pdf.multi_cell(0, 5, "This document was drafted by OrchestrAI. It is not a commitment of funds until a human approver signs the workflow in the approval inbox.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    path = OUT / f"{po_number}.pdf"
    pdf.output(str(path))
    return path


@tool(
    name="generate_purchase_order",
    description="Generate a Purchase Order PDF with line items, totals, chosen supplier, and terms.",
)
def generate_purchase_order(
    entities: dict | None = None,
    selected: dict | None = None,
    ranking: dict | None = None,
    workflow_id: str | None = None,
) -> ToolResult:
    entities = entities or {}
    if selected is None and isinstance(ranking, dict):
        selected = ranking.get("selected")
    if not selected:
        return ToolResult(ok=False, tool="generate_purchase_order", error="No selected supplier to put on the PO")
    po_number = _next_po()
    path = render_po(po_number=po_number, entities=entities, selected=selected, ranking=ranking)
    qty = int(entities.get("quantity") or selected.get("quantity") or 1)
    unit = float(selected.get("unit_price") or 0)
    total = float(selected.get("total") or unit * qty)
    return ToolResult(
        ok=True,
        tool="generate_purchase_order",
        data={
            "po_number": po_number,
            "path": str(path),
            "url": f"/artifacts/{path.name}",
            "line_items": [
                {
                    "description": entities.get("item"),
                    "qty": qty,
                    "unit_price": unit,
                    "total": total,
                }
            ],
            "grand_total": total,
            "currency": entities.get("currency", "PKR"),
            "supplier_id": selected.get("id"),
            "supplier_name": selected.get("name"),
            "workflow_id": workflow_id,
        },
        source="local",
    )
