"""Employee onboarding tools — account provisioning and equipment request."""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path
from typing import Any

from app.models import ToolResult
from app.tools import tool

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "generated"

_DEFAULT_ACCOUNTS = ["email", "slack", "jira", "github", "vpn"]
_DEFAULT_EQUIPMENT = ["laptop", "mouse", "keyboard", "monitor", "headset"]


def _latin(s: object) -> str:
    text = str(s or "")
    table = str.maketrans({
        "\u2014": "-", "\u2013": "-", "\u00b7": "|",
        "\u00d7": "x", "\u201c": '"', "\u201d": '"',
        "\u2018": "'", "\u2019": "'",
    })
    return text.translate(table).encode("latin-1", "replace").decode("latin-1")


@tool(
    name="provision_accounts",
    description="Mock tool: 'creates' system accounts for a new hire (email, Slack, Jira, GitHub, VPN). Logs each account provisioned. Deterministic — no real API calls.",
)
def provision_accounts(
    employee_name: str | None = None,
    start_date: str | None = None,
    accounts_needed: list | None = None,
) -> ToolResult:
    employee_name = str(employee_name or "New Hire")
    accounts = list(accounts_needed or _DEFAULT_ACCOUNTS)
    provisioned = []
    for acc in accounts:
        handle = str(acc).lower().replace(" ", "_")
        username = f"{employee_name.lower().replace(' ', '.')}@orchestrai.example"
        provisioned.append({
            "system": acc,
            "username": username if "email" in handle else f"{employee_name.lower().replace(' ', '.')}_{handle}",
            "status": "provisioned",
            "note": f"{acc} account created for {employee_name}",
        })
    return ToolResult(
        ok=True,
        tool="provision_accounts",
        data={
            "employee_name": employee_name,
            "start_date": start_date or date.today().isoformat(),
            "accounts": provisioned,
            "count": len(provisioned),
        },
        source="local",
    )


def _render_equipment_doc(
    *,
    doc_number: str,
    employee_name: str,
    start_date: str,
    equipment_list: list[str],
) -> Path:
    try:
        from fpdf import FPDF
        from fpdf.enums import XPos, YPos
        OUT.mkdir(parents=True, exist_ok=True)
        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=18)
        pdf.add_page()
        pdf.set_fill_color(14, 18, 24)
        pdf.rect(0, 0, 210, 28, "F")
        pdf.set_text_color(62, 224, 178)
        pdf.set_font("Helvetica", "B", 16)
        pdf.set_xy(12, 8)
        pdf.cell(186, 8, "OrchestrAI  /  EQUIPMENT REQUEST")
        pdf.set_text_color(180, 190, 200)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_xy(12, 16)
        pdf.cell(186, 6, "Generated by the onboarding workflow - requires manager approval before dispatch.")
        pdf.set_xy(12, 32)
        pdf.set_text_color(20, 24, 28)
        pdf.set_font("Helvetica", "B", 12)
        pdf.ln(8)
        pdf.cell(0, 8, _latin(f"Request Number: {doc_number}"))
        pdf.ln(8)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, _latin(f"Date: {date.today().isoformat()}"))
        pdf.ln(6)
        pdf.cell(0, 6, _latin(f"Employee: {employee_name}"))
        pdf.ln(6)
        pdf.cell(0, 6, _latin(f"Start Date: {start_date}"))
        pdf.ln(10)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 7, "Equipment Requested")
        pdf.ln(8)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_fill_color(232, 246, 240)
        pdf.cell(120, 8, "Item", border=1, fill=True)
        pdf.cell(65, 8, "Status", border=1, fill=True, align="C")
        pdf.ln()
        pdf.set_font("Helvetica", "", 9)
        for eq in equipment_list:
            pdf.cell(120, 8, _latin(str(eq).title()), border=1)
            pdf.cell(65, 8, "Pending Approval", border=1, align="C")
            pdf.ln()
        pdf.ln(10)
        pdf.set_font("Helvetica", "I", 9)
        pdf.multi_cell(0, 5,
            "This equipment request was drafted by OrchestrAI. Items will not be dispatched until a manager approves this workflow.",
            new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        path = OUT / f"{doc_number}.pdf"
        pdf.output(str(path))
        return path
    except Exception:
        # If fpdf2 unavailable, write a plain text stub
        OUT.mkdir(parents=True, exist_ok=True)
        path = OUT / f"{doc_number}.txt"
        path.write_text(
            f"Equipment Request {doc_number}\nEmployee: {employee_name}\nStart: {start_date}\nItems: {equipment_list}\n",
            encoding="utf-8",
        )
        return path


_eq_counter_file = OUT / "_eq_seq.json"


def _next_eq() -> str:
    OUT.mkdir(parents=True, exist_ok=True)
    seq = 1
    if _eq_counter_file.exists():
        try:
            seq = int(json.loads(_eq_counter_file.read_text()).get("n", 1))
        except Exception:
            seq = 1
    _eq_counter_file.write_text(json.dumps({"n": seq + 1}))
    return f"EQ-2026-{seq:04d}"


@tool(
    name="request_equipment",
    description="Generate an equipment request document (PDF) for a new hire. Reuses the fpdf2 pattern from documents.py.",
)
def request_equipment(
    employee_name: str | None = None,
    start_date: str | None = None,
    equipment_list: list | None = None,
    workflow_id: str | None = None,
) -> ToolResult:
    employee_name = str(employee_name or "New Hire")
    eq_items = list(equipment_list or _DEFAULT_EQUIPMENT)
    doc_number = _next_eq()
    start = start_date or date.today().isoformat()
    path = _render_equipment_doc(
        doc_number=doc_number,
        employee_name=employee_name,
        start_date=start,
        equipment_list=eq_items,
    )
    suffix = path.suffix.lower()
    mime = "application/pdf" if suffix == ".pdf" else "text/plain"
    return ToolResult(
        ok=True,
        tool="request_equipment",
        data={
            "doc_number": doc_number,
            "path": str(path),
            "url": f"/artifacts/{path.name}",
            "employee_name": employee_name,
            "start_date": start,
            "equipment_list": eq_items,
            "workflow_id": workflow_id,
        },
        source="local",
    )
